### ISSUE TITLE
Failed!! Did you run the code under the dataset, called something-something

### ISSUE THREAD

**Issue by Ai-is-light** [zhang-can/ECO-pytorch#1]
good work!
When I did try this repo by using the dataset, something-something, there was a odd bug. Although I have **all the data** of the something under the running folder, including the 
/20bn-datasets/20bn-something-something-v1/76110/00006.jpg' ,
 the code will stop owing to FileNotFoundError: [Errno 2] No such file or directory: '../20bn-datasets/20bn-something-something-v1/76110/img_00006.jpg'. 
Interestingly, this time is /76110/img-00006.jpg, while other time is /36265/img_00006.jpg. In Summary, it is changable!!
Thanks!
Looking forward to any answers!!
@zhang-can

**Comment by Ai-is-light** [comment]
Initializing TSN with base model: ECO.
TSN Configurations:
    input_modality:     RGB
    num_segments:       4
    new_length:         1
    consensus_module:   identity
    dropout_ratio:      0.5

['fc_final.weight', 'fc_final.bias']
/action_recognition/ECO-pytorch/tf_model_zoo/ECO/pytorch_load.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  normal(new_state_dict[k], 0, std)
/action_recognition/ECO-pytorch/tf_model_zoo/ECO/pytorch_load.py:62: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  constant(new_state_dict[k], 0)
/action_recognition/ECO-pytorch/models.py:91: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  normal(self.new_fc.weight, 0, std)
/action_recognition/ECO-pytorch/models.py:92: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  constant(self.new_fc.bias, 0)
/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 31 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 19 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 2 params, lr_mult: 1, decay_mult: 0
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "main.py", line 337, in <module>
    main()
  File "main.py", line 137, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 170, in train
    for i, (input, target) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 285, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 306, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/action_recognition/ECO-pytorch/dataset.py", line 104, in __getitem__
    return self.get(record, segment_indices)
  File "/action_recognition/ECO-pytorch/dataset.py", line 112, in get
    seg_imgs = self._load_image(record.path, p)
  File "/action_recognition/ECO-pytorch/dataset.py", line 54, in _load_image
    return [Image.open(os.path.join(directory, self.image_tmpl.format(idx))).convert('RGB')]
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../20bn-datasets/20bn-something-something-v1/59953/img_00001.jpg'

**Comment by zhang-can** [comment]
hi, @Ai-is-light . Thanks for your interest in this repo!

This is because the frames' names in something-something dataset doesn't have the prefix "img_", so you should delete the "--rgb_prefix img_" argument in the command.

**Note that I haven't test it on something-something dataset, and only ECO-Lite-4 has been tested on UCF101!**

**Comment by Ai-is-light** [comment]
@zhang-can Thanks.
Did you try this repo running under the ubuntu's docker environment? I met some problem when I ran this repo under the ubuntu's docker pytorch environment.
Looking forward to any replies.
Thanks

**Comment by Ai-is-light** [comment]
Initializing TSN with base model: ECO.
TSN Configurations:
    input_modality:     RGB
    num_segments:       4
    new_length:         1
    consensus_module:   identity
    dropout_ratio:      0.5
        
['fc_final.weight', 'fc_final.bias']
/workspace/action_recognition/ECO-pytorch/tf_model_zoo/ECO/pytorch_load.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  normal(new_state_dict[k], 0, std)
/workspace/action_recognition/ECO-pytorch/tf_model_zoo/ECO/pytorch_load.py:62: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  constant(new_state_dict[k], 0)
/workspace/action_recognition/ECO-pytorch/models.py:91: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  normal(self.new_fc.weight, 0, std)
/workspace/action_recognition/ECO-pytorch/models.py:92: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  constant(self.new_fc.bias, 0)
/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 31 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 19 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 2 params, lr_mult: 1, decay_mult: 0
Freezing BatchNorm2D except the first one.
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "main.py", line 337, in <module>
    main()
  File "main.py", line 137, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 170, in train
    for i, (input, target) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/opt/conda/lib/python3.6/site-packages/torch/storage.py", line 116, in _new_shared
    return cls._new_using_fd(size)

RuntimeError: unable to write to file </torch_51_2137600226> at /pytorch/aten/src/TH/THAllocator.c:383

**Comment by zhang-can** [comment]
Sorry for late reply!
I didn't test it under the ubuntu's docker environment.
Have u solved this problem?

**Comment by zhang-can** [comment]
If you have other questions, feel free to reopen the issue~
