### ISSUE TITLE
Total running time？

### ISSUE THREAD

**Issue by ivyvideo** [zhang-can/ECO-pytorch#10]
Thanks for your contribution!
I run the code successfully on Tesla M40, and it takes about 11 hours which is much longer than 3 hours mentioned in the origin paper. Is this normal?

**Comment by zhang-can** [comment]
Hi @ivyvideo ,

Thanks for your interest in this work.
In the original paper, the models were finetuned for **4k iterations**, which takes around 3 hours.
While in the code, I finetuned for **80 epochs**.

Take UCF101 training split 1 as example, there is 9537 videos, batch size is set to 32, so one epoch contains 9537/32=**~299 iterations**. 
**4k iterations** in the original paper means around 4000/299=**~14epochs**.

Therefore, the training time is normal.

**Comment by ivyvideo** [comment]
@zhang-can Thanks for your reply!
And I have noticed that in main.py, the input data is not put on GPU as shown follows:
```c++
target = target.cuda(async=True)
input_var = torch.autograd.Variable(input)
 target_var = torch.autograd.Variable(target)
```
only target data is turned into torch.cuda.FloatTensor, is this another reason for the low speed?

**Comment by zhang-can** [comment]
Hi @ivyvideo . Thanks~
I'm not sure about that. Maybe you can have a try and see whether there is an obvious improvement in terms of speed.
Any help will be appreciated.

**Comment by ivyvideo** [comment]
Alright! Appreciate it!
