### ISSUE TITLE
Error about checkpoint file when tried to test on a video 

### ISSUE THREAD

**Issue by ivyvideo** [zhang-can/ECO-pytorch#12]
Sorry to interrupt again...I have done the training part and the checkpoint file is generated, and I want to do  the inference task, so I write a demo using the .pth file and some frames cropped from a video in order to predict its class. But one error occurs:
```c++
Traceback (most recent call last):
  File "new_demo.py", line 105, in <module>
    main()
  File "new_demo.py", line 84, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home//anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.base_model.conv1_7x7_s2.weight" in state_dict
```
The code loading ckpt file is as follows:
```c++
checkpoint = torch.load(args.ckpt_file)
print checkpoint['state_dict'], type(checkpoint['state_dict'])
model.load_state_dict(checkpoint['state_dict'])
```
I have no idea what is wrong...

**Comment by zhang-can** [comment]
Hi @ivyvideo ,
The key name in model is "conv1_7x7_s2.weight" while the counterpart in your pth file is "module.base_model.conv1_7x7_s2.weight", you need to delete the "module.base_model." part.

For example, you can define a new state_dict by:
new_state_dict = {k[18:]: v for k, v in checkpoint['state_dict'].items()}

and then load the new state dict:
model.load_state_dict(new_state_dict)

**Comment by zhang-can** [comment]
@ivyvideo 
Yes, you can create a new ordered dict without the prefix.

**Comment by Zhangxinnian** [comment]
您好，请问测试代码是在那部分，我按照你写的要求成功在ucf101上训练，top1为91%左右，我想在视频里测试一下模型，请问该怎么做 @zhang-can ，非常期待您的回复
