### ISSUE TITLE
关于训练程序的使用方法

### ISSUE THREAD

**Issue by 124399839** [zhang-can/ECO-pytorch#14]
@zhang-can 您好，非常感谢你的工作，我安装readme文档中的方法进行实验，训练和测试数据分别产生了三个不同的文件，假设是train_list1.txt,train_list2.txt,train_list3.txt和val_list1.txt,val_list2.txt,val_list3.txt,
请问在执行python main.py ucf101 RGB <ucf101_rgb_train_list> <ucf101_rgb_val_list>应该如何将这三个文件传递给训练程序呢？谢谢！

**Comment by zhang-can** [comment]
Hi~Thanks for your interest in this repo.
For example, if you want to test split1, just use the following command:

```
python main.py ucf101 RGB train_list1.txt val_list1.txt
```

Or if you want to test split2, just use:

```
python main.py ucf101 RGB train_list2.txt val_list2.txt
```

**Comment by 124399839** [comment]
thanks ,I can run your code and train now.
