### ISSUE TITLE
test result on UCF101 with 16 segments each video

### ISSUE THREAD

**Issue by mangdian** [zhang-can/ECO-pytorch#18]
what's the result on testing set of UCF101 with 16 segments each video?

**Comment by zhang-can** [comment]
I only tested 4 frames, see as:

https://github.com/zhang-can/ECO-pytorch/issues/13#issuecomment-414100172

**Comment by mangdian** [comment]
@what about the results on Kinetics with 16 segments?

**Comment by mangdian** [comment]
@zhang-can what about the results on Kinetics with 16 segments?

**Comment by zhang-can** [comment]
Hi @mangdian ,

Please try our latest code in this repo:
https://github.com/mzolfaghari/ECO-pytorch
