### ISSUE TITLE
pretrained models cannot download

### ISSUE THREAD

**Issue by Usernamezhx** [zhang-can/ECO-pytorch#19]
first of all. thanks your code. i notice that you upload the ucf script sh . and I download the pretrained models by wget and the baidu disk. all failed. it show me that : 
![_20180919103408](https://user-images.githubusercontent.com/14010625/45727910-49d85d00-bbf8-11e8-9b03-9c6bb0d6e217.png)

**Comment by Usernamezhx** [comment]
![_20180919104045](https://user-images.githubusercontent.com/14010625/45727963-8310cd00-bbf8-11e8-8a94-e14a264d4716.png)

**Comment by zhang-can** [comment]
Hi @Usernamezhx ,

Did you try to unzip the file? The extension name of the model file is ".pth.tar". You shouldn't unzip the model file.

**Comment by Usernamezhx** [comment]
haha thank you very much . it works ! I am new  for pytorch. awkward! :p
