### ISSUE TITLE
在ucf101上finetune

### ISSUE THREAD

**Issue by Zhuysheng** [zhang-can/ECO-pytorch#20]
https://github.com/zhang-can/ECO-pytorch/blob/ef4cab77afece6a49c4ba1b6d0a271306a5a03ed/models.py#L321
当前向传播执行到这一步时，base_out的
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]],
       device='cuda:1', grad_fn=<DropoutBackward>)大多都成了nan，请问该如何解决

**Comment by zhang-can** [comment]
Hi @Zhuysheng ,

可能是预训练模型没有加载好，导致网络参数没有正确初始化。
Maybe this because your network params are not be properly initialized by pretrained model.

**Comment by ai1361720220000** [comment]
我也遇到了这个问题，请问下是怎么解决的
