### ISSUE TITLE
about the inference demo

### ISSUE THREAD

**Issue by Usernamezhx** [zhang-can/ECO-pytorch#23]
sooorry to bother you again :p 
  I want to test the online recognition. but the inference erro like this: `**RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58**`
only i set the batchsize to 2 and then it can work. but I find the eval will success when the batchsize is 15. below is the code:
![1](https://user-images.githubusercontent.com/14010625/46141021-54909300-c285-11e8-928b-f8f47ce4143c.png)
![2](https://user-images.githubusercontent.com/14010625/46141027-5bb7a100-c285-11e8-9626-0ba2fd56da15.png)
I test it on UCF101. thanks in advande

**Comment by Usernamezhx** [comment]
`input_var = data.cuda()` Does it matter?

**Comment by Usernamezhx** [comment]
I think I find the problem. I am not familar to pytorch. I only have one graph card . so I replace the code `model = torch.nn.DataParallel(model, device_ids=args.gpus).cuda()` to mode.cuda() . when I recover is was normal........

**Comment by forbiddenname** [comment]
Hi, how to  test the online recognition? Is Real-time Video Streaming ？
