### ISSUE TITLE
about the gen_dataset_lists.py

### ISSUE THREAD

**Issue by lianuo** [zhang-can/ECO-pytorch#3]
Thanks for you works on ECO, I just download your code and the DataSet ucf1101,
When I follow the instruction,I face such err:
could you help me check this error?
thanks~

================================ err ===================================

guo@guo-ubu:~/eng/ECO-pytorch-master$ python gen_dataset_lists.py ucf101 ~/eng/dataset/UCF-101/

Processing dataset ucf101:

- Parse frames under folder /home/guo/eng/dataset/UCF-101/

- 0/101 videos parsed

- Frame folder analysis done
- Writing list files for training/testing
Traceback (most recent call last):
  File "gen_dataset_lists.py", line 100, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/guo/eng/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 58, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/guo/eng/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 48, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'
guo@guo-ubu:~/eng/ECO-pytorch-master$

**Comment by zhang-can** [comment]
Have u extracted frames for the UCF101 dataset?
The files in your "~/eng/dataset/UCF-101/\*/\*" folder must be rgb images, not the original videos.

You can find some instructions on:
https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images

**Comment by lianuo** [comment]
@zhang-can thank you for your reply!
yes ,you are right,I have no rgb images yet.

**Comment by lianuo** [comment]
when I use use the "**bash scripts/build_file_list.sh**" in the https://github.com/yjxiong/temporal-segment-networks/tree/master/scripts, I got the same problem....

**Comment by zhang-can** [comment]
If you have other questions, feel free to reopen the issue~

**Comment by lianuo** [comment]
thanks ,I can run your code and train now.

**Comment by lianuo** [comment]
@zhang-can is there any thing new  in the "ECO-Lite-4F" compare with current on-line code? if there is ,is it possible to update the latest code? I know you are very busy....I just wonder the possibility...

thank you for your pytorch solution of ECO

**Comment by anguszxd** [comment]
Hi @zhang-can , Sorry to bother you. I also meet the same  problem as @lianuo met at first. I know that we should extract frames from original videos, under [https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images](url) this instructions. I briefly read the scrips in that TSN project, and find this script `extract-frames-and-optical-flow-images` is used to extract optical flow, which is not necessary in ECO. So, should I run  `extract-frames-and-optical-flow-images` in TSN project to extract the frames?

**Comment by lianuo** [comment]
@anguszxd you can modify the code to avoid the generation of optical flow infomation.

**Comment by anguszxd** [comment]
Hi @lianuo, thanks. You're right. I've just extracted frames from videos without calculating optical flow. It works.

**Comment by gaopeng-eugene** [comment]
Can you tell me how to extract frames without calculating optical flow?

**Comment by Morethan123** [comment]
@lianuo @zhang-can    Hi, could i ask you a question please? In the first, the second args i set is  frame_root(i extract it by codes but not TSN works). Why i still face the same KeyError: 'v_ApplyEyeMakeup_g08_c01' and other error informations are also the same.I notice that processed pictures are rgb frames from original videos in UCF101. I guess you are success in running this codes. Hope you can help me. Thank you!

**Comment by Morethan123** [comment]
@lianuo  By the way, There are two levels of directories on my extracted frame pictures. The first is 101 class file(ApplyEyeMakeup - Yoyo), The second directory is video name under per action class, Such as 'v_ApplyEyeMakeup_g08_c01'. What is your folder arrangement ? My command is       python gen_dataset_lists.py ucf101 /media/shaojie/Documentation/Mo_ECO/ECO-pytorch/data/dataset/UCF101/UCF-101_jpg

**Comment by JasonYangZi** [comment]
> @lianuo By the way, There are two levels of directories on my extracted frame pictures. The first is 101 class file(ApplyEyeMakeup - Yoyo), The second directory is video name under per action class, Such as 'v_ApplyEyeMakeup_g08_c01'. What is your folder arrangement ? My command is python gen_dataset_lists.py ucf101 /media/shaojie/Documentation/Mo_ECO/ECO-pytorch/data/dataset/UCF101/UCF-101_jpg

你的问题解决了吗？我遇到了同样的问题，我的指令为 python gen_dataset_lists.py ucf101 /home/jiang123/Avideos/jiang123/videos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"

**Comment by JasonYangZi** [comment]
@Morethan123 你的问题解决了吗？我遇到了同样的问题，我的指令为 python gen_dataset_lists.py ucf101 /home/jiang/Avideos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"

**Comment by yeboqxc** [comment]
> @Morethan123你的问题解决了吗？我遇到了同样的问题，我的操作为python gen_dataset_lists.py ucf101 /home/jiang/Avideos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"

Hello, have you solved this problem? I have converted the video into frames, the directory structure is like this ucf101/ApplyEyeMakeup--the last one/v_ApplyEyeMakeup_g01_c01--the last one/00001.jpg...the last one, how can I solve this problem? Or is there something wrong with my run command? Can you give some suggestions? thanks

**Comment by JasonYangZi** [comment]
> > @Morethan123你的问题解决了吗？我遇到了同样的问题，我的操作为python gen_dataset_lists.py ucf101 /home/jiang/Avideos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"
> 
> Hello, have you solved this problem? I have converted the video into frames, the directory structure is like this ucf101/ApplyEyeMakeup--the last one/v_ApplyEyeMakeup_g01_c01--the last one/00001.jpg...the last one, how can I solve this problem? Or is there something wrong with my run command? Can you give some suggestions? thanks

在我的印象中是修改遍历的路径 frame_folders = glob.glob(os.path.join(path, '*'))

**Comment by yeboqxc** [comment]
> 谢谢，我现在可以运行您的代码并进行训练。

可以加QQ细聊嘛？841628586，不胜感激

**Comment by yeboqxc** [comment]
> > > @Morethan123你的问题解决了吗？我遇到了同样的问题，我的操作为python gen_dataset_lists.py ucf101 /home/jiang/Avideos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"
> > 
> > 
> > 你好，这个问题你解决了吗？我已经把视频转成帧了，目录结构是这样的 ucf101/ApplyEyeMakeup--最后一个/v_ApplyEyeMakeup_g01_c01--最后一个/00001.jpg...最后一个，这个问题怎么解决？还是我的运行命令有问题？你能给一些建议吗？谢谢
> 
> 在我的印象中是修改遍历的路径 frame_folders = glob.glob(os.path.join(path, '*'))

可以加Q细聊嘛？841628586，不胜感激！

**Comment by HuZia777** [comment]
parse frames under folder /tmp/temperal/EVEN_DATASET/save
0 videos parsed
200 videos parsed
frame folder analysis done
Traceback (most recent call last):
  File "gen_label_ucf101.py", line 99, in <module>
    lists = build_split_list(spl,f_info,i)
  File "gen_label_ucf101.py", line 88, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "gen_label_ucf101.py", line 77, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_Basketball_g01_c01'
I have this problem ,could you help me solve this problem?

**Comment by HuZia777** [comment]
> Thanks for you works on ECO, I just download your code and the DataSet ucf1101, When I follow the instruction,I face such err: could you help me check this error? thanks~
> 
> ================================ err ===================================
> 
> guo@guo-ubu:~/eng/ECO-pytorch-master$ python gen_dataset_lists.py ucf101 ~/eng/dataset/UCF-101/
> 
> Processing dataset ucf101:
> 
> * Parse frames under folder /home/guo/eng/dataset/UCF-101/
> * 0/101 videos parsed
> * Frame folder analysis done
> * Writing list files for training/testing
>   Traceback (most recent call last):
>   File "gen_dataset_lists.py", line 100, in 
>   lists = build_split_list(split_tp, f_info, i, shuffle)
>   File "/home/guo/eng/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 58, in build_split_list
>   train_rgb_list, train_flow_list = build_set_list(split[0])
>   File "/home/guo/eng/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 48, in build_set_list
>   frame_dir = frame_info[0][item[0]]
>   KeyError: 'v_ApplyEyeMakeup_g08_c01'
>   guo@guo-ubu:~/eng/ECO-pytorch-master$

I also have this problem?could you tell me how to solve it?
