### ISSUE TITLE
Difference between pre-trained ECOLite models

### ISSUE THREAD

**Issue by pencilzhang** [zhang-can/ECO-pytorch#38]
Hi, I have downloaded the ECOLite pre-trained models following the instructions given here https://github.com/mzolfaghari/ECO-pytorch. 
I am not sure what is the difference between the two pre-trained ECOLite models: eco_lite_rgb_16F_kinetics_v3.pth.tar and ECO_Lite_rgb_model_Kinetics.pth.tar
Thanks!

**Comment by chen-ming2019** [comment]
the performance of v3 is better than the other .

**Comment by Morethan123** [comment]
@pencilzhang @chen-ming2019  我从作者那无法下载预训练好的模型，导致没办法成功运行main.py，你们能否提供给我这几个已经下载好的.pth文件？谢谢

**Comment by pencilzhang** [comment]
> @pencilzhang @chen-ming2019 我从作者那无法下载预训练好的模型，导致没办法成功运行main.py，你们能否提供给我这几个已经下载好的.pth文件？谢谢

I can send you the pre-trained models please drop me an email if you still need them. Thanks.

**Comment by pencilzhang** [comment]
@Morethan123  I can send the pre-trained models. Please drop me an email if you still need them, thanks!

**Comment by Liquor520** [comment]
> 
> 
> @Morethan123 I can send the pre-trained models. Please drop me an email if you still need them, thanks!

Hi, I also want to run the main.py file with the training model. Would you like to share it if it’s convenient for you? My WeChat: LIQUOR_LCA
