### ISSUE TITLE
how to modify the number of classes?

### ISSUE THREAD

**Issue by lianuo** [zhang-can/ECO-pytorch#6]
though the num_class is set at the begin of the main.py as follow ,but it seems not being used in the program,  could you give me some suggestion ？
thank you~
-------------------main.py-------------------------
if args.dataset == 'ucf101':
        num_class = 101
    elif args.dataset == 'hmdb51':
        num_class = 51
    elif args.dataset == 'kinetics':
        num_class = 400
    elif args.dataset == 'something':
        num_class = 174

**Comment by lianuo** [comment]
I modify the tf-model-zoo/ECO/pytorch_load.py __init__(  num_classes=101) ,it seems ok now.

**Comment by AVCarreiro** [comment]
Hi there, I could use the num_class outside and see it reflected in the fc_final output, but the argument num_classes in ECO module seems to never be used (or referenced) in the file.

**Comment by zhang-can** [comment]
Hi @AVCarreiro ,

In models.py, 

def _prepare_tsn(self, num_class):

Here, "num_classes" is used to define the fc layer.

**Comment by lianuo** [comment]
@zhang-can thank you~
